CREATE TABLE IF NOT EXISTS client (
                        id BIGINT GENERATED BY DEFAULT as identity PRIMARY KEY,
                        fullName VARCHAR(150) NOT NULL,
                        idData VARCHAR(255) NOT NULL,
                        familyStatus VARCHAR(255),
                        address VARCHAR(255),
                        phoneNumber VARCHAR(255) NOT NULL,
                        workingExperience VARCHAR(255),
                        loanAmount DECIMAL(19, 2)
);
CREATE TABLE IF NOT EXIST loanApplication (
                                 id BIGINT generated by default as identity PRIMARY KEY,
                                 client_id BIGINT NOT NULL,
                                 status BOOLEAN,
                                 term INT CHECK (term >= 1 AND term <= 360),
                                 approvedAmount DECIMAL(19, 2),
                                 FOREIGN KEY (client_id) REFERENCES client(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXIST loanContract (
                              id BIGINT generated by default as identity PRIMARY KEY,
                              loan_application_id BIGINT NOT NULL,
                              signatureDate DATE,
                              signature_status BOOLEAN,
                              FOREIGN KEY (loan_application_id) REFERENCES loanApplication(id) ON DELETE CASCADE ON UPDATE CASCADE
);